site_name: Xignage Platform Docs
site_description: Xignage Documentation
site_url: https://tstaisyu.github.io/xignage-docs
repo_url: https://github.com/tstaisyu/xignage-docs

theme:
  name: material
  language: ja
  features:
    - navigation.indexes
#extra:
#  copyright:
#    - text: "最終更新: {{ git_revision_date_localized }}"

plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: ja
          name: 日本語
          default: true
        - locale: en
          name: English
      reconfigure_material: true
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
      timezone: Asia/Tokyo
      locale: ja

extra_javascript:
  - https://unpkg.com/mermaid@10.9.1/dist/mermaid.min.js
  - javascripts/mermaid-init.js
  - javascripts/last-updated-top.js

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - attr_list
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Architecture:
      - Overview: architecture/index.md
#      - Software Stack: architecture/software_stack.md
  - Hardware:
      - Overview: hardware/index.md
      - System Composition: hardware/system_composition.md
      - Electrical:
          - BOM (Rev A): hardware/electrical/bom_rev_a.md
      - Mechanical:
          - Frame Overview: hardware/mechanical/frame_overview.md
      - Revisions (Baseline): hardware/revisions.md
  - Packages:
      - Overview: packages/index.md
      - signage-server: 
          - overview: packages/signage-server/index.md
          - Runtime:
              - Overview: packages/signage-server/runtime/index.md
              - Express App: packages/signage-server/runtime/express-app.md
              - Chromium Manager: packages/signage-server/runtime/chromium-manager.md
          - API:
              - overview: packages/signage-server/api/index.md
              - ルーティング: packages/signage-server/api/routes.md
              - コントローラー: packages/signage-server/api/controllers.md
          - サービス(services):
              - overview: packages/signage-server/services/index.md
              - System / Platform: packages/signage-server/services/system.md
              - Network / Registration: packages/signage-server/services/network.md
              - Media / Content: packages/signage-server/services/media.md
          - コンポーネント:
              - overview: packages/signage-server/components/index.md
              - クラウドソケット: packages/signage-server/components/cloud-socket.md
              - ローカルソケット: packages/signage-server/components/local-socket.md
          - ユーティリティ: packages/signage-server/utils.md
          - フロントページ:
              - overview: packages/signage-server/public/index.md
              - ページ一覧: packages/signage-server/public/pages.md
              - JS モジュール: packages/signage-server/public/js.md
          - 設定(config): packages/signage-server/config.md
      - signage-jetson:
          - Overview: packages/signage-jetson/index.md
          - setup(000-099): packages/signage-jetson/units/setup-000-099.md
          - setup(100-199): packages/signage-jetson/units/setup-100-199.md
          - setup(200-599): packages/signage-jetson/units/setup-200-599.md
          - setup(600-899): packages/signage-jetson/units/setup-600-899.md
          - setup(900-999): packages/signage-jetson/units/setup-900-999.md
          - メトリクス送信サービス（metrics）: packages/signage-jetson/components/metrics-service.md
          - インフラ / AWS IoT 証明書: packages/signage-jetson/infra/aws-iot-certs.md
          - Wi-Fi ブートツール: packages/signage-jetson/components/wifi-boot-tools.md
          - アップデートツール: packages/signage-jetson/components/update-tools.md
          - 依存パッケージ（deps）: packages/signage-jetson/deps.md
          - 環境変数リファレンス: packages/signage-jetson/files/config-sh.md
          - ユーティリティ関数リファレンス: packages/signage-jetson/files/functions-sh.md
      - signage-aws-nodejs:
          - overview: packages/signage-aws-nodejs/index.md
          - Runtime: packages/signage-aws-nodejs/runtime.md
          - ルーティング: packages/signage-aws-nodejs/routes.md
          - ソケット(socket): packages/signage-aws-nodejs/socket.md
          - サービス(services): packages/signage-aws-nodejs/services.md
          - CI / GitHub Actions: ci/workflows/signage-aws-nodejs/ci.md
      - signage-admin-ui:
          - overview: packages/signage-admin-ui/index.md
          - API contract: packages/signage-admin-ui/api.md
          - コンポーネント: packages/signage-admin-ui/components.md
          - ページ / ルーティング: packages/signage-admin-ui/pages.md
          - フック: packages/signage-admin-ui/hooks.md
          - セットアップ: packages/signage-admin-ui/setup.md
          - CI / GitHub Actions: ci/workflows/signage-admin-ui/ci.md
      - xignage-edge-detection:
          - Overview: packages/xignage-edge-detection/index.md
          - セットアップ: packages/xignage-edge-detection/setup.md
          - 設定: packages/xignage-edge-detection/config.md
          - API (Pipeline/Detectors/IO): packages/xignage-edge-detection/api.md
          - CLI: packages/xignage-edge-detection/cli.md
          - Runtime & Troubleshooting: packages/xignage-edge-detection/runtime.md
          - CI / GitHub Actions: ci/workflows/xignage-edge-detection/ci.md
#      - jetson-ab-flash: packages/jetson-ab-flash/index.md
#  - ADR: adr/index.md
  - CI / Automation:
      - Overview: ci/index.md
      - Workflows (signage-jetson):
          - Setup CI: ci/workflows/signage-jetson/setup-ci.md
          - Release TAR: ci/workflows/signage-jetson/release-tar.md
          - Build Patches: ci/workflows/signage-jetson/build-patches.md
          - APT License Check: ci/workflows/signage-jetson/apt-license-check.md
          - Python License Check: ci/workflows/signage-jetson/python-license-check.md
          - Metrics CI: ci/workflows/signage-jetson/metrics-ci.md
          - Update Release Badge: ci/workflows/signage-jetson/update-release-badge.md
      - Workflows (signage-server):
          - Server CI: ci/workflows/signage-server/server-ci.md
          - License Check: ci/workflows/signage-server/license-check.md
          - Release TAR (server): ci/workflows/signage-server/release-tar.md
          - Update Release Badge (server): ci/workflows/signage-server/update-release-badge.md
  - Mobile Apps:
      - Xignage（adalo）: apps/xignage-adalo/index.md
