site_name: Xignage Platform Docs
site_description: Xignage Documentation
site_url: https://tstaisyu.github.io/xignage-docs
repo_url: https://github.com/tstaisyu/xignage-docs

theme:
  name: material
  language: ja
  features:
    - navigation.indexes

plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: ja
          name: 日本語
          default: true
        - locale: en
          name: English
      reconfigure_material: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - attr_list
  - footnotes
  - pymdownx.superfences

nav:
  - Home: index.md
#  - Architecture:
#      - Overview: architecture/index.md
#      - Software Stack: architecture/software_stack.md
  - Packages:
      - signage-server: 
          - overview: packages/signage-server/index.md
          - API:
              - overview: packages/signage-server/api/index.md
              - ルーティング: packages/signage-server/api/routes.md
              - コントローラー: packages/signage-server/api/controllers.md
          - ユーティリティ: packages/signage-server/utils.md
          - 設定(config): packages/signage-server/config.md
#          - cloudsocket: packages/signage-server/components/cloud-socket.md
#      - signage-aws-nodejs: packages/signage-aws-nodejs/index.md
#      - signage-admin-ui: packages/signage-admin-ui/index.md
      - signage-jetson:
          - Overview: packages/signage-jetson/index.md
          - setup(000-099): packages/signage-jetson/units/setup-000-099.md
          - setup(100-199): packages/signage-jetson/units/setup-100-199.md
          - setup(200-599): packages/signage-jetson/units/setup-200-599.md
          - setup(600-899): packages/signage-jetson/units/setup-600-899.md
          - setup(900-999): packages/signage-jetson/units/setup-900-999.md
          - メトリクス送信サービス（metrics）: packages/signage-jetson/components/metrics-service.md
          - インフラ / AWS IoT 証明書: packages/signage-jetson/infra/aws-iot-certs.md
          - Wi-Fi ブートツール: packages/signage-jetson/components/wifi-boot-tools.md
          - アップデートツール: packages/signage-jetson/components/update-tools.md
          - 依存パッケージ（deps）: packages/signage-jetson/deps.md
          - 環境変数リファレンス: packages/signage-jetson/files/config-sh.md
          - ユーティリティ関数リファレンス: packages/signage-jetson/files/functions-sh.md
#      - jetson-ab-flash: packages/jetson-ab-flash/index.md
#  - ADR: adr/index.md
  - CI / Automation:
      - Overview: ci/index.md
      - Workflows:
          - Setup CI: ci/workflows/setup-ci.md
          - Release TAR: ci/workflows/release-tar.md
          - Build Patches: ci/workflows/build-patches.md
          - APT License Check: ci/workflows/apt-license-check.md
          - Python License Check: ci/workflows/python-license-check.md
          - Metrics CI: ci/workflows/metrics-ci.md
          - Update Release Badge: ci/workflows/update-release-badge.md