site_name: Xignage Platform Docs
site_description: Xignage Documentation
site_url: https://tstaisyu.github.io/xignage-docs
repo_url: https://github.com/tstaisyu/xignage-docs

theme:
  name: material
  language: ja
  features:
    - navigation.indexes

plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: ja
          name: 日本語
          default: true
        - locale: en
          name: English
      reconfigure_material: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - attr_list
  - footnotes
  - pymdownx.superfences

nav:
  - Home: index.md
#  - Architecture:
#      - Overview: architecture/index.md
#      - Software Stack: architecture/software_stack.md
  - Developers:
      - Packages:
#          - signage-server: 
#              - overview: developers/packages/signage-server/index.md
#              - cloudsocket: developers/packages/signage-server/components/cloud-socket.md
#          - signage-aws-nodejs: developers/packages/signage-aws-nodejs/index.md
#          - signage-admin-ui: developers/packages/signage-admin-ui/index.md
          - signage-jetson:
              - Overview: developers/packages/signage-jetson/index.md
              - setup(000-099): developers/packages/signage-jetson/units/setup_000_099.md
              - setup(100-199): developers/packages/signage-jetson/units/setup_100_199.md
              - setup(200-599): developers/packages/signage-jetson/units/setup_200_599.md
#          - jetson-ab-flash: developers/packages/jetson-ab-flash/index.md
#  - Business: business/index.md
#  - KPI Overview: kpi_overview/index.md
#  - ADR: adr/index.md
