site_name: Xignage Platform Docs
site_description: Xignage Documentation
site_url: https://tstaisyu.github.io/xignage-docs
repo_url: https://github.com/tstaisyu/xignage-docs

theme:
  name: material
  language: ja

plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: ja
          name: 日本語
          default: true
        - locale: en
          name: English
      nav_translations:
        en:
          ホーム: Home
          アーキテクチャ: Architecture
          概要: Overview
          ソフトウェアスタック: Software Stack
          ビジネス: Business
          KPI 概要: KPI Overview
          ADR: ADR

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - attr_list
  - footnotes
  - pymdownx.superfences

nav:
  - ホーム: index.md
  - アーキテクチャ:
      - 概要: architecture/index.md
      - ソフトウェアスタック: architecture/software_stack.md
  - ビジネス: business/index.md
  - KPI 概要: kpi_overview/index.md
  - ADR: adr/index.md
