name: docs-quality
on:
  push:
    paths:
      - '**/*.md'
      - 'mkdocs.yml'
  pull_request:
    paths:
      - '**/*.md'
      - 'mkdocs.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli
      - name: Run markdownlint
        run: markdownlint '**/*.md'

  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run lychee link checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress --verbose '**/*.md'
