name: verify-diagrams
on:
  push:
    paths-ignore: ["README.md", "*.md"]
  pull_request:

jobs:
  diff-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install drawio CLI & Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          sudo snap install drawio

      - name: Re-export diagrams and check diff
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1600x1200x24" \
            bash scripts/export-diagrams.sh
          git diff --exit-code
